#!/usr/bin/env bash

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root (use sudo)" >&2
   exit 1
fi

cd ..
if [ -d ./cpp-utils ]; then
    rm -rf ./cpp-utils
fi
git clone https://github.com/Rrominet/cpp-utils
cd ./cpp-utils
chmod +x ./build-n-install
./build-n-install
cd ../fxlauncher-backend
mkdir -p ./build

cd ./build
chmod +x ../make
chmod +x ../install
../make release keep-same libs="../../cpp-utils_dependencies" fm="../../cpp-utils"
../install
