#!/usr/bin/env bash
#
mkdir -p /opt/fxlauncher
rm -vf /opt/fxlauncher/fxlauncher
cp -v ./fxlauncher /opt/fxlauncher/fxlauncher
cp -v ./version /opt/fxlauncher/version
cp -v ./dependencies /opt/fxlauncher/dependencies
chmod +x /opt/fxlauncher/fxlauncher
chmod 777 -R /opt/fxlauncher

rm -vf /usr/local/bin/fxlauncher
ln -s /opt/fxlauncher/fxlauncher /usr/local/bin/fxlauncher

echo "fxlauncher installed."
